<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipios;
class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipios::insert([
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Ahuachapán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Apaneca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Atiquizaya',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Concepción de Ataco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'El Refugio',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Guaymango',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Jujutla',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'San Francisco Menéndez',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'San Lorenzo Ahuachapán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'San Pedro Puxtla',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Tacuba',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>1, 'municipio'=>'Turín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Cinquera',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Dolores',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Guacotecti',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Ilobasco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Jutiapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'San Isidro',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Sensuntepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Tejutepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>2, 'municipio'=>'Victoria',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Agua Caliente',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Arcatao',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Azacualpa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Chalatenango',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Citalá',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Comalapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Concepción Quezaltepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Dulce Nombre de María',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'El Carrizal',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'El Paraíso',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'La Laguna',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'La Palma',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'La Reina',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Las Vueltas',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Nombre de Jesús',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Nueva Concepción',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Nueva Trinidad',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Ojos de Agua',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Potonico',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Antonio de la Cruz',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Antonio Los Ranchos',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Fernando',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Francisco Lempa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Francisco Morazán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Ignacio',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Isidro Labrador',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San José Cancasque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San José Las Flores',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Luis del Carmen',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Miguel de Mercedes',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'San Rafael',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Santa Rita',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>3, 'municipio'=>'Tejutla',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Candelaria',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Cojutepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'El Carmen',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'El Rosario',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Monte San Juan',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Oratorio de Concepción',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'San Bartolomé Perulapía',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'San Cristóbal',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'San José Guayabal',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'San Pedro Perulapán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'San Rafael Cedros',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'San Ramón',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Santa Cruz Analquito',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Santa Cruz Michapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Suchitoto',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>4, 'municipio'=>'Tenancingo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Antiguo Cuscatlán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Chiltiupán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Ciudad Arce',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Colón',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Comasagua',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Huizúcar',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Jayaque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Jicalapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'La Libertad',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Nuevo Cuscatlán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Quezaltepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Sacacoyo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'San José Villanueva',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'San Juan Opico',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'San Matías',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'San Pablo Tacachico',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Santa Tecla',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Talnique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Tamanique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Teotepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Tepecoyo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>5, 'municipio'=>'Zaragoza',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Cuyultitán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'El Rosario La Paz',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Jerusalén',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Mercedes La Ceiba',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Olocuilta',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Paraíso de Osorio',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Antonio Masahuat',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Emigdio',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Francisco Chinameca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Juan Nonualco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Juan Talpa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Juan Tepezontes',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Luis La Herradura',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Luis Talpa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Miguel Tepezontes',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Pedro Masahuat',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Pedro Nonualco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'San Rafael Obrajuelo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Santa María Ostuma',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Santiago Nonualco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Tapalhuaca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>6, 'municipio'=>'Zacatecoluca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Anamorós',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Bolívar',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Concepción de Oriente',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Conchagua',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'El Carmen La Unión',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'El Sauce',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Intipucá',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'La Unión',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Lislique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Meanguera del Golfo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Nueva Esparta',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Pasaquina',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Polorós',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'San Alejo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'San José',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Santa Rosa de Lima',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Yayantique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>7, 'municipio'=>'Yucuaiquín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Arambala',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Cacaopera',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Chilanga',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Corinto',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Delicias de Concepción',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'El Divisadero',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'El Rosario Morazán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Gualococti',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Guatajiagua',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Joateca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Jocoaitique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Jocoro',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Lolotiquillo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Meanguera',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Osicala',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Perquín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'San Carlos',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'San Fernando Morazán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'San Francisco Gotera',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'San Isidro Morazán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'San Simón',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Sensembra',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Sociedad',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Torola',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Yamabal',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>8, 'municipio'=>'Yoloaiquín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Carolina',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Chapeltique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Chinameca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Chirilagua',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Ciudad Barrios',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Comacarán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'El Tránsito',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Lolotique',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Moncagua',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Nueva Guadalupe',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Nuevo Edén de San Juan',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Quelepa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'San Antonio',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'San Gerardo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'San Jorge',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'San Luis de la Reina',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'San Miguel',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'San Rafael Oriente',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Sesori',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>9, 'municipio'=>'Uluazapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Aguilares',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Apopa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Ayutuxtepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Ciudad Delgado',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Cuscatancingo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'El Paisnal',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Guazapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Ilopango',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Mejicanos',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Nejapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Panchimalco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Rosario de Mora',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'San Marcos',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'San Martín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'San Salvador',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Santiago Texacuangos',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Santo Tomás',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Soyapango',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>10, 'municipio'=>'Tonacatepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Apastepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Guadalupe',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'San Cayetano Istepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'San Esteban Catarina',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'San Ildefonso',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'San Lorenzo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'San Sebastián',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'San Vicente',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Santa Clara',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Santo Domingo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Tecoluca',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Tepetitán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>11, 'municipio'=>'Verapaz',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Candelaria de la Frontera',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Chalchuapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Coatepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'El Congo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'El Porvenir',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Masahuat',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Metapán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'San Antonio Pajonal',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'San Sebastián Salitrillo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Santa Ana',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Santa Rosa Guachipilín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Santiago de la Frontera',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>12, 'municipio'=>'Texistepeque',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Acajutla',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Armenia',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Caluco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Cuisnahuat',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Izalco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Juayúa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Nahuizalco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Nahulingo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Salcoatitán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'San Antonio del Monte',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'San Julián',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Santa Catarina Masahuat',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Santa Isabel Ishuatán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Santo Domingo de Guzmán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Sonsonate',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>13, 'municipio'=>'Sonzacate',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Alegría',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Berlín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'California',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Concepción Batres',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'El Triunfo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Ereguayquín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Estanzuelas',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Jiquilisco',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Jucuapa',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Jucuarán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Mercedes Umaña',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Nueva Granada',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Ozatlán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Puerto El Triunfo',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'San Agustín',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'San Buenaventura',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'San Dionisio',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'San Francisco Javier',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Santa Elena',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Santa María',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Santiago de María',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Tecapán',],
            ['created_at' => date('Y-m-d H:m:s'), 'updated_at' => date('Y-m-d H:m:s'), 'departamento_fk'=>14, 'municipio'=>'Usulután',],
        ]);
    }
}
